export const tasks = [
    { 
      id: 1, 
      classProgress1: 'green', 
      classProgress2: 'blue', 
      classProgress3: 'gray', 
      textTask: 'Проверить отчёт', 
      fio: 'Иван Иванов', 
      numberTask: 'SPL-001', 
      typeIcon: 'analitics', 
      stateIcon: 'coordination',

      productIcon:1,
      textProductIcon: 'Simplanum',
      typeProductIcon: 'ios',
      version: '1.1',
      questionText: 'Вопрос по процедуре'

    },
    { 
      id: 2, 
      classProgress1: 'blue', 
      classProgress2: 'green', 
      classProgress3: 'gray', 
      textTask: 'Создать дизайн страницы', 
      fio: 'Анна Петрова', 
      numberTask: 'SPL-002', 
      typeIcon: 'design', 
      stateIcon: 'execution',

      productIcon:1,
      textProductIcon: 'figma',
      typeProductIcon: 'android',
      version: '12',
      questionText: 'Вопрос по вопросу'
    },
    { 
      id: 3, 
      classProgress1: 'gray', 
      classProgress2: 'green', 
      classProgress3: 'blue', 
      textTask: 'Разработать API', 
      fio: 'Виктор Сидоров', 
      numberTask: 'SPL-003', 
      typeIcon: 'dev', 
      stateIcon: 'review', 

      productIcon:1,
      textProductIcon: 'figma',
      typeProductIcon: 'backend',
      version: '1.2',
      questionText: 'Вопрос по вопросу 1'
    },
    { 
      id: 4, 
      classProgress1: 'green', 
      classProgress2: 'gray', 
      classProgress3: 'blue', 
      textTask: 'Тестирование модуля 2', 
      fio: 'Мария Кузнецова', 
      numberTask: 'SPL-004', 
      typeIcon: 'qa', 
      stateIcon: 'test',
      productIcon:1,
      textProductIcon: 'figma',
      typeProductIcon: 'iosload',
      version: '1.2',
      questionText: 'Вопрос по вопросу 3' 
    },
    { 
      id: 5, 
      classProgress1: 'blue', 
      classProgress2: 'blue', 
      classProgress3: 'green', 
      textTask: 'Исправить баг', 
      fio: 'Алексей Смирнов', 
      numberTask: 'SPL-005', 
      typeIcon: 'error-critical', 
      stateIcon: 'done',
      productIcon:2,
      textProductIcon: 'figma',
      typeProductIcon: 'webapp',
      version: '12',
      questionText: 'Вопрос по вопросу 4' 
    },
    { 
      id: 6, 
      classProgress1: 'gray', 
      classProgress2: 'green', 
      classProgress3: 'red', 
      textTask: 'Создать юнит-тесты', 
      fio: 'Екатерина Фёдорова', 
      numberTask: 'SPL-006', 
      typeIcon: 'qa', 
      stateIcon: 'coordination',
      productIcon:1,
      textProductIcon: 'figma',
      typeProductIcon: 'website',
      version: '62',
      questionText: 'Вопрос по вопросу 5' 
    },
    { 
      id: 7, 
      classProgress1: 'green', 
      classProgress2: 'red', 
      classProgress3: 'blue', 
      textTask: 'Обновить документацию 6', 
      fio: 'Михаил Попов', 
      numberTask: 'SPL-007', 
      typeIcon: 'analitics', 
      stateIcon: 'deployment',
      productIcon:1,
      textProductIcon: 'figma',
      typeProductIcon: 'webapp',
      version: '52',
      questionText: 'Вопрос по вопросу 7' 
    },
    { 
      id: 8, 
      classProgress1: 'blue', 
      classProgress2: 'green', 
      classProgress3: 'gray', 
      textTask: 'Провести ревью кода', 
      fio: 'Ольга Соколова', 
      numberTask: 'SPL-008', 
      typeIcon: 'dev-back', 
      stateIcon: 'review',
      productIcon:2,
      textProductIcon: 'visual',
      typeProductIcon: 'website',
      version: '42',
      questionText: 'Вопрос по вопросу 8' 
    },
    { 
      id: 9, 
      classProgress1: 'red', 
      classProgress2: 'blue', 
      classProgress3: 'green', 
      textTask: 'Подготовить релиз', 
      fio: 'Дмитрий Крылов', 
      numberTask: 'SPL-009', 
      typeIcon: 'dev', 
      stateIcon: 'done',
      productIcon:1,
      textProductIcon: 'figma',
      typeProductIcon: 'backend',
      version: '32',
      questionText: 'Вопрос по вопросу 9' 
    },
    { 
      id: 10, 
      classProgress1: 'green', 
      classProgress2: 'gray', 
      classProgress3: 'blue', 
      textTask: 'Исправить некритичные ошибки', 
      fio: 'Сергей Николаев', 
      numberTask: 'SPL-010', 
      typeIcon: 'error-nonimportant', 
      stateIcon: 'coordination',
      productIcon:1,
      textProductIcon: 'figma',
      typeProductIcon: 'backend',
      version: '22',
      questionText: 'Вопрос по вопросу 10' 
    },
  ];
  